export const ATTRIBUTIONS = [
  {
    name: 'Basketball Net',
    nameUrl: 'https://sketchfab.com/3d-models/basketball-net-a845be1db4c141be92ceadebfb5b38f0',
    author: '1-3D.com',
    authorUrl: 'https://sketchfab.com/1-3D.com',
    via: 'Sketchfab',
  },
  {
    name: 'Bean Bag Chair',
    nameUrl: 'https://poly.pizza/m/1MFMOaz3zqe',
    author: 'CMHT Oculus',
    authorUrl: 'https://poly.pizza/u/CMHT%20Oculus',
    via: 'Poly Pizza',
  },
  {
    name: 'Bonsai Tree',
    nameUrl: 'https://sketchfab.com/3d-models/bonsai-1fa23a78daed444d88296e25d9c19e66',
    author: 'local.yany',
    authorUrl: 'https://sketchfab.com/local.yany',
    via: 'Sketchfab',
  },
  {
    name: 'Book',
    author: 'Norbert Kurucz',
    authorUrl: 'https://poly.pizza/u/Norbert%20Kurucz',
    via: 'Poly Pizza',
  },
  {
    name: 'Coffee Table',
    nameUrl: 'https://sketchfab.com/3d-models/noguchi-coffee-table-8f8a3dbd45534152b5771c36cc4742d9',
    author: 'Deborah Kumagai',
    authorUrl: 'https://sketchfab.com/3dmaedchen',
    via: 'Sketchfab',
  },
  {
    name: 'Cookie Jar',
    nameUrl: 'https://sketchfab.com/3d-models/cookies-in-the-jar-372cc5bca9e54c579d8399a18e686b24',
    author: 'sheana',
    authorUrl: 'https://sketchfab.com/sheana',
    via: 'Sketchfab',
  },
  {
    name: 'Corner Shelf',
    nameUrl: 'https://sketchfab.com/3d-models/corner-wall-shelf-c5e0ad84a2d44c9b9cc3bef27cd77bcd',
    author: 'kakou3991',
    authorUrl: 'https://sketchfab.com/kakou3991',
    via: 'Sketchfab',
  },
  {
    name: 'Couch',
    nameUrl: 'https://poly.pizza/m/1kwsjhpY84',
    author: 'Quaternius',
    authorUrl: 'https://poly.pizza/u/Quaternius',
    via: 'Poly Pizza',
  },
  {
    name: 'Frame',
    nameUrl: 'https://sketchfab.com/3d-models/picture-frame-1520-dimensions-2a75286422e64948b1d6626bc9c6d47d',
    author: 'Fred Drabble',
    authorUrl: 'https://sketchfab.com/FredDrabble',
    via: 'Sketchfab',
  },
  {
    name: 'Info Button',
    nameUrl: 'https://poly.pizza/m/5-29GUpKKKq',
    author: 'Paul Hoover',
    authorUrl: 'https://poly.pizza/u/Paul%20Hoover',
    via: 'Poly Pizza',
  },
  {
    name: 'Kanye West\'s Graduation Bear',
    nameUrl: 'https://sketchfab.com/3d-models/kanye-west-graduation-bear-18687fc90634474a821dc48c62ba70e6',
    author: 'vxnzz',
    authorUrl: 'https://sketchfab.com/vxnzz',
    via: 'Sketchfab',
  },
  {
    name: 'MacBook',
    nameUrl: 'https://sketchfab.com/3d-models/macbook-289c013e6c0541f498d4c6b40045db88',
    author: 'M I H',
    authorUrl: 'https://sketchfab.com/imamulhasan',
    via: 'Sketchfab',
  },
  {
    name: 'Neon Character Signs',
    nameUrl: 'https://sketchfab.com/3d-models/neon-sign-letters-and-elements-a5330a94391945a493a87b07d118fe02',
    author: 'oparaskos',
    authorUrl: 'https://sketchfab.com/oparaskos',
    via: 'Sketchfab',
  },
  {
    name: 'Neon Lucky Cat Light Sign',
    nameUrl: 'https://sketchfab.com/3d-models/neon-signs-307e887d740649f88fbc77b061f3a742',
    author: 'Shalmon',
    authorUrl: 'https://sketchfab.com/nashalanandas',
    via: 'Sketchfab',
  },
  {
    name: 'Nintendo Switch',
    nameUrl: 'https://sketchfab.com/3d-models/nintendo-switch-b8e8670918944c6398174e90c129b926',
    author: 'Bjarne Stokhof',
    authorUrl: 'https://sketchfab.com/stokhuis',
    via: 'Sketchfab',
  },
  {
    name: 'Noodle Cup',
    nameUrl: 'https://sketchfab.com/3d-models/tau-noodle-cup-74399ab3073d47d196621eecee0bfad3',
    author: 'Squishy',
    authorUrl: 'https://sketchfab.com/squidyed',
    via: 'Sketchfab',
  },
  {
    name: 'Pac-Man Arcade Machine',
    nameUrl: 'https://sketchfab.com/3d-models/pacman-arcade-animation-0b43f85af5384ea4bac5d6e2d3cbd008',
    author: 'Daniel Brück',
    authorUrl: 'https://sketchfab.com/daniel.brueck',
    via: 'Sketchfab',
  },
  {
    name: 'Remote Control',
    nameUrl: 'https://poly.pizza/m/5pcD_YZujab',
    author: 'Poly by Google',
    authorUrl: 'https://poly.pizza/u/Poly%20by%20Google',
    via: 'Poly Pizza',
  },
  {
    name: 'Rug',
    nameUrl: 'https://sketchfab.com/3d-models/low-poly-psx-style-neutral-rugs-pack-ffa7b81303c6427b8c1a5a3b5b7161b8',
    author: 'Icevanilla',
    authorUrl: 'https://sketchfab.com/vanillao03',
    via: 'Sketchfab',
  },
  {
    name: 'TV Stand',
    nameUrl: 'https://sketchfab.com/3d-models/tv-stand-55612f6c24dd4b189993ef80f00791c9',
    author: 'LightSwitch',
    authorUrl: 'https://sketchfab.com/edwardlewis450',
    via: 'Sketchfab',
  },
]
